export enum ECopyVariant {
  // hex
  HEX_WITH_SHARP = 'HEX_WITH_SHARP',
  HEX_WITHOUT_SHARP = 'HEX_WITHOUT_SHARP',
  HEX_LOWERCASE_WITH_SHARP = 'HEX_LOWERCASE_WITH_SHARP',
  HEX_LOWERCASE_WITHOUT_SHARP = 'HEX_LOWERCASE_WITHOUT_SHARP',
  // rgb
  CSS_RGB = 'CSS_RGB',
  RGB_COMMA_SEPARATED = 'RGB_COMMA_SEPARATED',
  // hsl
  CSS_HSL = 'CSS_HSL',
  HSL_COMMA_SEPARATED = 'HSL_COMMA_SEPARATED',
  // cmyk
  CMYK_FUNCTION = 'CMYK_FUNCTION',
  CMYK_COMMA_SEPARATED = 'CMYK_COMMA_SEPARATED',
}
